version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
